version: '3'

services:
  web:
    build: .
    image: "elementary"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL : jdbc:mysql://localhost:3306/elementarySchool
      SPRING_DATASOURCE_USERNAME : root
      SPRING_DATASOURCE_PASSWORD : Qwer123!

  db:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Qwer123!
      MYSQL_DATABASE: elementarySchool